"""Cria tabela agendamentos

Revision ID: 0829d3d6214b
Revises: 0f3f58d88ed4
Create Date: 2026-06-30 13:42:01.869555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0829d3d6214b'
down_revision = '0f3f58d88ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista', sa.String(length=100), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('data_saida', sa.Date(), nullable=False),
    sa.Column('hora_saida', sa.Time(), nullable=False),
    sa.Column('data_retorno', sa.Date(), nullable=False),
    sa.Column('hora_retorno', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    # ### end Alembic commands ###
