"""usuarios e autenticacao

Revision ID: e26d2b6717fd
Revises: 8ca5d6f9c77a
Create Date: 2026-07-20 14:15:19.997535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e26d2b6717fd'
down_revision = '8ca5d6f9c77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
